on: push
name: Push docs to website
jobs:
  web-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: FTP upload
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: trashbyte.io
        username: githubftp
        password: ${{ secrets.ftp_password }}
        server-dir: "singularity/"
        exclude: |
          **/.git*
          **/.git*/**
          LICENSE.txt
          readme.md
